### ISSUE TITLE
ES Module

### ISSUE THREAD

**Issue by gr2m** [semantic-release/env-ci#154]
Part of our efforts to migrate `semantic-release` to native ES Modules: https://github.com/semantic-release/semantic-release/issues/2133

A main motivation, just like for @semantic-release itself, is that `env-ci` depends on many packages by @sindresorhus, and we are locked out from updating them as all of Sindre's packages are being upgraded to ESM. We have several dependencies we cannot upgrade for that reason: https://github.com/semantic-release/env-ci/pulls

We are aware that `env-ci` is widely used beyond @semantic-release, so we will try to maintain the current version (v5.x.x) for a while. But v6 will most likely be ESM, and we won't release any breaking changes to the CJS Version (v5) any more.

Please let us know if you have any questions or concerns

### Todos

- [x] remove `fromentries`, use native `Object.fromEntries()` instead

**Comment by travi** [comment]
released as https://github.com/semantic-release/env-ci/releases/tag/v8.0.0
