### ISSUE TITLE
Support WoodpeckerCI

### ISSUE THREAD

**Issue by 6543** [semantic-release/env-ci#218]
## Support [WoodpeckerCI](https://github.com/woodpecker-ci)

Documentation: https://woodpecker-ci.org/docs/usage/environment#built-in-environment-variables

Environment variables:
- service detection: `CI=woodpecker`
- Branch: `CI_COMMIT_SOURCE_BRANCH`
- Commit sha: `CI_COMMIT_SHA`
- Is Pull request: `CI_COMMIT_PULL_REQUEST` != ""
- Pull request: `CI_COMMIT_PULL_REQUEST`
- Build number: `CI_BUILD_NUMBER`

**Comment by travi** [comment]
We welcome PRs to contribute new services like this one
