### ISSUE TITLE
Incorrect buildkite slug

### ISSUE THREAD

**Issue by vio** [semantic-release/env-ci#333]
## Bug

The slug value on buildkite has an incorrect format: `ORG/ORG/PROJECT`.  Both `ORG` and `PROJECT` values refer to the buildkite specific configuration and can differ from the repository slug.

- CI: buildkite
- Build link: https://buildkite.com/rltv/example/builds/17#018c534b-f9e0-4102-88f1-370ede16ad52

```
  relative-ci:agent env-ci environment variables {
  isCi: true,
  name: 'Buildkite',
  service: 'buildkite',
  build: '17',
  buildUrl: 'https://buildkite.com/rltv/example/builds/17',
  commit: '38649ff7dc00526a539a4e0759d25fbe8c7d537f',
  tag: '',
  branch: 'main',
  slug: 'rltv/rltv/example',
  pr: '1',
  isPr: true,
  prBranch: 'update-agent',
  root: '/opt/homebrew/var/buildkite-agent/builds/mbp22-local-1/rltv/example'
```

Documentation: https://buildkite.com/docs/pipelines/environment-variables#buildkite-environment-variables

buildkite does not provide a specific environment variable for the actual repository slug, but provides the full git repo URL: `BUILDKITE_REPO`.  A similar method as for https://github.com/semantic-release/env-ci/issues/249#issue-1480194988 can be used to extract the real repository slug.

**Comment by travi** [comment]
PRs welcome
